# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Chris Kurdziel
tagline:          'The personal blog of Chris Kurdziel'
description:      'If you wish to make an apple pie from scratch, you must first blog about it online.'
url:              https://chriskurdziel.com
#baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Chris Kurdziel'
  url:            https://chriskurdziel.com

include:
  - _pages

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-gist

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
